# Generated by Django 5.1.3 on 2024-12-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='film_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='film',
            name='review',
            field=models.IntegerField(verbose_name='Отзыв'),
        ),
    ]
